from enum import Enum, auto


class Phoneme(Enum):
    # Non-Rhotic Vowels
    long_a = auto()
    short_a = auto()
    long_e = auto()
    short_e = auto()
    long_i = auto()
    short_i = auto()
    long_o = auto()
    short_o = auto()
    long_u = auto()
    short_u = auto()
    long_oo = auto()
    short_oo = auto()
    ah = auto()
    oy = auto()
    aw = auto()
    ow = auto()
    schwa = auto()

    # Rhotic Vowels
    r_a = auto()
    r_ah = auto()
    r_e = auto()
    r_i = auto()
    r_o = auto()
    r_u = auto()
    r_stressed_neutral = auto()
    r_oo = auto()
    r_aw = auto()
    r_ow = auto()
    r_schwa = auto()

    # Paired Consonants
    p = auto()
    b = auto()
    t = auto()
    d = auto()
    unvoiced_th = auto()
    voiced_th = auto()
    ch = auto()
    j = auto()
    k = auto()
    g = auto()
    qu = auto()
    gu = auto()
    unvoiced_x = auto()
    voiced_x = auto()
    f = auto()
    v = auto()
    s = auto()
    z = auto()
    sh = auto()
    zh = auto()

    # Unpaired Consonants
    h = auto()
    l = auto()
    r = auto()
    m = auto()
    n = auto()
    ng = auto()
    w = auto()
    wh = auto()
    y = auto()
